### ISSUE TITLE
Please add example pictures with tutorials, such as for Windows 10.

### ISSUE THREAD

**Issue by hdavidzhu** [cmaher92/GoDigitalWithUs#52]
http://www.godigitalwith.us/tutorials/5

There are some great descriptions on here. For even more clarity, I think screenshots could be added so that the user would never get lost. Also pictures (or even video) are worth a thousand words, right?

**Comment by lesliekimm** [comment]
@hdavidzhu hahahaha i think none of us have windows, but great suggestions! and we'll definitively have to add screenshots.
