### ISSUE TITLE
Consider providing the XKCD example on creating passwords.

### ISSUE THREAD

**Issue by hdavidzhu** [cmaher92/GoDigitalWithUs#53]
http://www.godigitalwith.us/tutorials/5

"Your password should be long and difficult to guess..."

For this section, I think that this should be provided as reference: https://xkcd.com/936/

**Comment by lesliekimm** [comment]
haha @hdavidzhu using ramp camp material :) i like it

**Comment by extrajordanary** [comment]
link above now invalid - please provide more info to help clarify which tutorial you mean

**Comment by hdavidzhu** [comment]
@extrajordanary It's the one what talked about creating good passwords. I can't find it either anymore. I guess this doesn't apply anymore if that tutorial has been moved. Feel free to close this issue.
